/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-03-12 00:17:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class GUISettings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/Head.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("        require([\r\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/RequireIncludes.jsp", out, true);
      out.write("\r\n");
      out.write("        ], function() {\r\n");
      out.write("            require([\r\n");
      out.write("                \"net/apachegui/GUISettings\",\r\n");
      out.write("                \"dojox/grid/DataGrid\",\r\n");
      out.write("                \"dojo/data/ItemFileWriteStore\",\r\n");
      out.write("                \"dijit/ProgressBar\",\r\n");
      out.write("                \"dijit/form/Select\",\r\n");
      out.write("                \"dojo/dom\",\r\n");
      out.write("                \"dojo/parser\",\r\n");
      out.write("                \"dojo/domReady!\"\r\n");
      out.write("            ], function(GUISettings, DataGrid, ItemFileWriteStore, ProgressBar, Select, dom, parser) {\r\n");
      out.write("                parser.parse();\r\n");
      out.write("\r\n");
      out.write("                net.apachegui.Main.getInstance().init('GUISettings');\r\n");
      out.write("\r\n");
      out.write("                dom.byId(\"guiSettingsBody\").style.visibility='visible';\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${theme}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"guiSettingsBody\" style=\"visibility:hidden\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/Init.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"display: none;\">\r\n");
      out.write("    <ul dojoType=\"dijit.Menu\" id=\"settings_menu\">\r\n");
      out.write("        <div id=\"editSettingsMenuItem\" dojoType=\"dijit.MenuItem\">\r\n");
      out.write("            Edit\r\n");
      out.write("        </div>\r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"updateServerRootDialog\" title=\"Update\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"updateServerRootForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='updateSettingServerRoot'>\r\n");
      out.write("                        Server Root:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"updateSettingServerRoot\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"serverRootUpdate\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"serverRootUpdateCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"updateConfDirectoryDialog\" title=\"Update\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"updateConfDirectoryForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='updateSettingConfDirectory'>\r\n");
      out.write("                        Configuration Directory:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"updateSettingConfDirectory\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"configurationDirectoryUpdate\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"configurationDirectoryUpdateCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"updateConfFileDialog\" title=\"Update\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"updateConfFileForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='updateSettingConfFile'>\r\n");
      out.write("                        Configuration File:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"updateSettingConfFile\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"configurationFileUpdate\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"configurationFileUpdateCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"updateLogDirectoryDialog\" title=\"Update\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"updateLogDirectoryForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='updateSettingLogDirectory'>\r\n");
      out.write("                        Log Directory:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"updateSettingLogDirectory\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"logDirectoryUpdate\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"logDirectoryUpdateCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"updateModulesDirectoryDialog\" title=\"Update\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"updateModulesDirectoryForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='updateSettingModulesDirectory'>\r\n");
      out.write("                        Modules Directory:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"updateSettingModulesDirectory\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"modulesDirectoryUpdate\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"modulesDirectoryUpdateCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"updateBinFileDialog\" title=\"Update\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"updateBinFileForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='updateSettingBinFile'>\r\n");
      out.write("                        Binary File:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"updateSettingBinFile\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"binaryFileUpdate\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"binaryFileUpdateCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"updateUsernameDialog\" title=\"Update\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"updateUsernameForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='updateSettingUsername'>\r\n");
      out.write("                        Username:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"updateSettingUsername\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"usernameUpdate\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"usernameUpdateCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"updatePasswordDialog\" title=\"Update\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"updatePasswordForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='updateSettingPassword1'>\r\n");
      out.write("                        Password1:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"updateSettingPassword1\" type=\"password\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='updateSettingPassword2'>\r\n");
      out.write("                        Password2:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"updateSettingPassword2\" type=\"password\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"passwordUpdate\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"passwordUpdateCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"updateThemeDialog\" title=\"Update\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"updateThemeForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='claro'>\r\n");
      out.write("                        Claro:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"radio\" name=\"themeType\" id=\"claro\" value=\"claro\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='nihilo'>\r\n");
      out.write("                        Nihilo:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"radio\" name=\"themeType\" id=\"nihilo\" value=\"nihilo\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='soria'>\r\n");
      out.write("                        Soria:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"radio\" name=\"themeType\" id=\"soria\" value=\"soria\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='tundra'>\r\n");
      out.write("                        Tundra:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"radio\" name=\"themeType\" id=\"tundra\" value=\"tundra\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"themeUpdate\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"themeUpdateCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"updateEncodingDialog\" title=\"Update\" style=\"display: none\">\r\n");
      out.write("\r\n");
      out.write("    <p>This GUI uses the UTF-8 character encoding for updates to all text files. This is the preferred character encoding for web pages throughout the internet and cannot be changed.</p>\r\n");
      out.write("    <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("        <button id=\"encodingUpdateCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("            Ok\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div data-dojo-type=\"dijit/Dialog\" id=\"updateEnableAuthenticationDialog\" title=\"Update\" style=\"display: none\">\r\n");
      out.write("    <form data-dojo-type=\"dijit/form/Form\" id=\"updateEnableAuthenticationForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='updateEnableAuthentication'>\r\n");
      out.write("                        Enable Authentication:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select name=\"updateEnableAuthentication\" id=\"updateEnableAuthentication\" data-dojo-type=\"dijit/form/Select\">\r\n");
      out.write("                        <option value=\"yes\">\r\n");
      out.write("                            yes\r\n");
      out.write("                        </option>\r\n");
      out.write("                        <option value=\"no\">\r\n");
      out.write("                            no\r\n");
      out.write("                        </option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"enableAuthenticationUpdate\" data-dojo-type=\"dijit/form/Button\" type=\"button\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"enableAuthenticationUpdateCancel\" data-dojo-type=\"dijit/form/Button\" type=\"button\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"guiInfoDialog\" title=\"GUI Info\" style=\"display: none\" >\r\n");
      out.write("    <table id=\"guiInfoTable\">\r\n");
      out.write("        <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("            <td width=\"125\">\r\n");
      out.write("                Version:\r\n");
      out.write("            </td>\r\n");
      out.write("            <td width=\"200\">\r\n");
      out.write("                ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${version}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("            <td>\r\n");
      out.write("                Homepage:\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <a target=\"_blank\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${website}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${website}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("            <td>\r\n");
      out.write("                Support:\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <a target=\"_blank\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${supportWebsite}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${supportWebsite}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a><br>\r\n");
      out.write("                <a href=\"mailto:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${supportAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${supportAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</a>\r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("        <button id=\"guiInfoClose\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("            Ok\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"appLayout\" class=\"demoLayout\" data-dojo-type=\"dijit.layout.BorderContainer\" data-dojo-props=\"design: 'headline'\">\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/Heading.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/Menu.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"centerPanel\" class=\"centerPanel\" data-dojo-type=\"dijit.layout.ContentPane\" data-dojo-props=\"region: 'center'\">\r\n");
      out.write("        <div class=\"dijitDialogPaneContentArea\"><h3>Application Settings</h3></div>\r\n");
      out.write("            <span dojoType=\"dojo.data.ItemFileWriteStore\" jsId=\"settingsStore\" url=\"../web/GUISettings/Current\" urlPreventCache=\"true\">\r\n");
      out.write("            </span>\r\n");
      out.write("        <table id=\"settingsGrid\" dojoType=\"dojox.grid.DataGrid\" jsId=\"settingsGrid\" store=\"settingsStore\" query=\"{ name: '*' }\" clientSort=\"false\" selectable=\"true\" style=\"width: 100%;\" autoHeight=\"true\" rowSelector=\"20px\">\r\n");
      out.write("            <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th width=\"200px\" field=\"name\">\r\n");
      out.write("                    Setting Name\r\n");
      out.write("                </th>\r\n");
      out.write("                <th width=\"auto\" field=\"value\">\r\n");
      out.write("                    Setting Value\r\n");
      out.write("                </th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div>\r\n");
      out.write("            <button id=\"serverInfoButton\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Apache Info\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"guiInfoButton\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                &nbsp;GUI Info&nbsp;&nbsp;\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"newServerButton\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                New Server&nbsp;\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
