/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-03-12 00:17:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import net.apachegui.global.Constants;

public final class Init_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div dojoType=\"net.apachegui.NoCloseDialog\" id=\"initDialogInstallationType\" title=\"How was Apache installed?\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"initFormInstallationType\">\r\n");
      out.write("        <h4>Please select your Apache Server installation method.</h4>\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td colspan=\"2\">\r\n");
      out.write("                    <p> Select the Package option if you have installed Apache through your Operating Systems package manager.\r\n");
      out.write("                        The Apache installation is typically spread out through your operating system.</p>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td width=\"60px\">\r\n");
      out.write("                    <label for='package'>\r\n");
      out.write("                        Package:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"radio\" name=\"installType\" id=\"package\" value=\"package\" checked=\"checked\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td colspan=\"2\">\r\n");
      out.write("                    <p> Select the Source option if you have compiled the Apache server from its source code.\r\n");
      out.write("                        The entire Apache installation is typically contained in one Server Root directory.</p>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td width=\"60px\">\r\n");
      out.write("                    <label for='source'>\r\n");
      out.write("                        Source:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"radio\" name=\"installType\" id=\"source\" value=\"source\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button dojoType=\"dijit.form.Button\" type=\"submit\">\r\n");
      out.write("                OK\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"net.apachegui.NoCloseDialog\" id=\"initDialogSource\" title=\"Apache Source Parameters\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"initFormSource\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <label for='serverRootSource'>\r\n");
      out.write("                            Server Root:\r\n");
      out.write("                            </label>\r\n");
      out.write("                       </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"serverRootSource\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='usernameSource'>\r\n");
      out.write("                        Username:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"usernameSource\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='password1Source'>\r\n");
      out.write("                        Password:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" type=\"password\" id=\"password1Source\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='password2Source'>\r\n");
      out.write("                        Password:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" type=\"password\" id=\"password2Source\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='enableAuthenticationSource'>\r\n");
      out.write("                        Enable Authentication:\r\n");
      out.write("                        <span id=\"enableAuthenticationSourceTooltip\" class=\"warningTooltip\" onmouseover=\"dijit.Tooltip.defaultPosition=['below', 'above']\"></span>\r\n");
      out.write("                        <div class=\"dijitHidden\">\r\n");
      out.write("                            <div data-dojo-type=\"dijit.Tooltip\" data-dojo-props=\"connectId:'enableAuthenticationSourceTooltip'\">\r\n");
      out.write("                                <div class=\"warningDialog\">");
      out.print(Constants.AUTHENTICATION_ADVISORY);
      out.write("</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select name=\"enableAuthenticationSource\" id=\"enableAuthenticationSource\" data-dojo-type=\"dijit/form/Select\">\r\n");
      out.write("                        <option value=\"yes\" selected=\"selected\">\r\n");
      out.write("                            yes\r\n");
      out.write("                        </option>\r\n");
      out.write("                        <option value=\"no\">\r\n");
      out.write("                            no\r\n");
      out.write("                        </option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"hideSourceOption\" dojoType=\"dijit.form.Button\" type=\"button\" ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(">\r\n");
      out.write("                Back\r\n");
      out.write("            </button>\r\n");
      out.write("            <button dojoType=\"dijit.form.Button\" type=\"submit\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"net.apachegui.NoCloseDialog\" id=\"initDialogPackage\" title=\"Apache Package Parameters\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"initFormPackage\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='operatingSystemSuggestionPackage'>\r\n");
      out.write("                        Operating System Suggestion (Optional):\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select name=\"operatingSystemSuggestionPackage\" id=\"operatingSystemSuggestionPackage\" data-dojo-type=\"dijit/form/Select\">\r\n");
      out.write("                        <option value=\"select\" selected=\"selected\">\r\n");
      out.write("                            Select\r\n");
      out.write("                        </option>\r\n");
      out.write("                        <option value=\"mac\">\r\n");
      out.write("                            Mac OSX\r\n");
      out.write("                        </option>\r\n");
      out.write("                        <option value=\"debian\">\r\n");
      out.write("                            Debian, Ubuntu, Other Debian variants\r\n");
      out.write("                        </option>\r\n");
      out.write("                        <option value=\"fedora\">\r\n");
      out.write("                            Fedora, CentOS, RHEL, other fedora variants\r\n");
      out.write("                        </option>\r\n");
      out.write("                        <option value=\"suse32\">\r\n");
      out.write("                            OpenSUSE and SLES 32 bit\r\n");
      out.write("                        </option>\r\n");
      out.write("                        <option value=\"suse64\">\r\n");
      out.write("                            OpenSUSE and SLES 64 bit\r\n");
      out.write("                        </option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='serverRootPackage'>\r\n");
      out.write("                        Server Root:\r\n");
      out.write("                        </label>\r\n");
      out.write("                   </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"serverRootPackage\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='confFilePackage'>\r\n");
      out.write("                        Primary Configuration File:\r\n");
      out.write("                        </label>\r\n");
      out.write("                   </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"confFilePackage\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='confDirectoryPackage'>\r\n");
      out.write("                        Configuration Directory:\r\n");
      out.write("                        </label>\r\n");
      out.write("                   </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"confDirectoryPackage\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='logDirectoryPackage'>\r\n");
      out.write("                        Log Directory:\r\n");
      out.write("                       </label>\r\n");
      out.write("                   </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"logDirectoryPackage\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='modulesDirectoryPackage'>\r\n");
      out.write("                        Modules Directory:\r\n");
      out.write("                       </label>\r\n");
      out.write("                   </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"modulesDirectoryPackage\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='binFilePackage'>\r\n");
      out.write("                        Binary File:\r\n");
      out.write("                       </label>\r\n");
      out.write("                   </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"binFilePackage\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='usernamePackage'>\r\n");
      out.write("                        Username:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"usernamePackage\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='password1Package'>\r\n");
      out.write("                        Password:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" type=\"password\" id=\"password1Package\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='password2Package'>\r\n");
      out.write("                        Password:\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" type=\"password\" id=\"password2Package\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='enableAuthenticationPackage'>\r\n");
      out.write("                        Enable Authentication:\r\n");
      out.write("                        <span id=\"enableAuthenticationPackageTooltip\" class=\"warningTooltip\" onmouseover=\"dijit.Tooltip.defaultPosition=['below', 'above']\"></span>\r\n");
      out.write("                        <div class=\"dijitHidden\">\r\n");
      out.write("                            <div data-dojo-type=\"dijit.Tooltip\" data-dojo-props=\"connectId:'enableAuthenticationPackageTooltip'\">\r\n");
      out.write("                                <div class=\"warningDialog\">");
      out.print(Constants.AUTHENTICATION_ADVISORY);
      out.write("</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select name=\"enableAuthenticationPackage\" id=\"enableAuthenticationPackage\" data-dojo-type=\"dijit/form/Select\">\r\n");
      out.write("                        <option value=\"yes\" selected=\"selected\">\r\n");
      out.write("                            Yes\r\n");
      out.write("                        </option>\r\n");
      out.write("                        <option value=\"no\">\r\n");
      out.write("                            No\r\n");
      out.write("                        </option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"hidePackageOption\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Back\r\n");
      out.write("            </button>\r\n");
      out.write("            <button dojoType=\"dijit.form.Button\" type=\"submit\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/views/Init.jsp(122,85) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${windows == true}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("style=\"display:none;\"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
