/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-03-12 00:17:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"leftCol\"  data-dojo-type=\"dojox.layout.ExpandoPane\" data-dojo-props=\"region: 'left', splitter: true\">\r\n");
      out.write("        <ul dojoType=\"dijit.Menu\" id=\"tree_menu\" style=\"display: none;\">\r\n");
      out.write("            <div id=\"renameMenuItem\" dojoType=\"dijit.MenuItem\" iconClass=\"dijitEditorIcon dijitEditorIconUndo\">\r\n");
      out.write("                Rename\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"newMenuItem\" dojoType=\"dijit.MenuItem\" iconClass=\"dijitEditorIcon dijitEditorIconSave\">\r\n");
      out.write("                New\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"cutMenuItem\" dojoType=\"dijit.MenuItem\" iconClass=\"dijitEditorIcon dijitEditorIconCut\">\r\n");
      out.write("                Cut\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"copyMenuItem\" dojoType=\"dijit.MenuItem\" iconClass=\"dijitEditorIcon dijitEditorIconCopy\">\r\n");
      out.write("                Copy\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"pasteMenuItem\" dojoType=\"dijit.MenuItem\" iconClass=\"dijitEditorIcon dijitEditorIconPaste\">\r\n");
      out.write("                Paste\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"deleteMenuItem\" dojoType=\"dijit.MenuItem\" iconClass=\"dijitEditorIcon dijitEditorIconDelete\">\r\n");
      out.write("                Delete\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"refreshMenuItem\" dojoType=\"dijit.MenuItem\" iconClass=\"dijitEditorIcon dijitEditorIconRedo\">\r\n");
      out.write("                Refresh\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"uploadMenuItem\" dojoType=\"dijit.MenuItem\">\r\n");
      out.write("                Upload\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"downloadMenuItem\" dojoType=\"dijit.MenuItem\">\r\n");
      out.write("                Download\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"searchMenuItem\" dojoType=\"dijit.MenuItem\">\r\n");
      out.write("                Search\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"newTabMenuItem\" dojoType=\"dijit.MenuItem\">\r\n");
      out.write("                New Tab\r\n");
      out.write("            </div>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!--  <div dojoType=\"dojo.data.ItemFileWriteStore\" jsId=\"apacheStore\" url=\"../web/Menu/rest\">\r\n");
      out.write("        </div>-->\r\n");
      out.write("        <div dojoType=\"dojox.data.JsonRestStore\" jsId=\"apacheStore\" target=\"");
      out.print((request.getContextPath() + "/web/Menu/rest") );
      out.write("\" labelAttribute=\"name\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div dojoType=\"dijit.tree.ForestStoreModel\" jsId=\"apacheModel\" store=\"apacheStore\"\r\n");
      out.write("            rootId=\"apacheRoot\" rootLabel=\"Apache\" childrenAttrs=\"children\" deferItemLoadingUntilExpand=\"true\" >\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div dojoType=\"net.apachegui.RefreshableTree\" id=\"menuTree\" model=\"apacheModel\" openOnClick=\"true\" showRoot=\"false\" persist=\"true\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"newFileDialog\" title=\"New File\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"newFileForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='newFileFilename'>\r\n");
      out.write("                        Filename:\r\n");
      out.write("                        </label>\r\n");
      out.write("                   </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"newFileFilename\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    Type:\r\n");
      out.write("                   </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input type=\"radio\" name=\"newFileFileType\" id=\"newFileFileTypeFile\" value=\"newFileFileTypeFile\" checked=\"checked\">\r\n");
      out.write("                      <label for=\"newFileFileTypeFile\">File</label>\r\n");
      out.write("                      <input type=\"radio\" name=\"newFileFileType\" id=\"newFileFileTypeDirectory\" value=\"Directory\">\r\n");
      out.write("                      <label for=\"newFileFileTypeDirectory\">Directory</label>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"newFileCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("            <button dojoType=\"dijit.form.Button\" type=\"submit\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"renameFileDialog\" title=\"Rename File\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"renameFileForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    Old Filename:\r\n");
      out.write("                   </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div id=\"renameFileOldFile\"></div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                <td>\r\n");
      out.write("                    <label for='renameFileFilename'>\r\n");
      out.write("                        New Filename:\r\n");
      out.write("                        </label>\r\n");
      out.write("                   </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"renameFileFilename\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"renameFileCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Cancel\r\n");
      out.write("            </button>\r\n");
      out.write("            <button dojoType=\"dijit.form.Button\" type=\"submit\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"uploadFileDialog\" title=\"Upload File\" style=\"width: 700px; height: auto;\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"uploadFileForm\" action=\"../web/UploadFile\" enctype=\"multipart/form-data\" method=\"post\">\r\n");
      out.write("        <input type=\"hidden\" name=\"uploadDirectoryName\" id=\"uploadDirectoryName\"/>\r\n");
      out.write("        <input type=\"hidden\" name=\"currentURL\" id=\"currentURL\"/>\r\n");
      out.write("        \r\n");
      out.write("         <div>\r\n");
      out.write("            <fieldset>\r\n");
      out.write("                <legend>Upload Files</legend>\r\n");
      out.write("                <input name=\"uploadFile\" multiple=\"true\" type=\"file\" id=\"uploadFile\" data-dojo-type=\"dojox/form/Uploader\" data-dojo-props=\"label: 'Select Files'\">\r\n");
      out.write("                <div id=\"upload_file_list\" data-dojo-type=\"dojox/form/uploader/FileList\" data-dojo-props=\"uploaderId: 'uploadFile'\"></div>\r\n");
      out.write("            </fieldset>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"uploadFileCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Done\r\n");
      out.write("            </button>\r\n");
      out.write("            <button dojoType=\"dijit.form.Button\" type=\"submit\">\r\n");
      out.write("                Submit\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"searchConfigurationDialog\" title=\"Search Configuration\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"searchConfigurationForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <label>\r\n");
      out.write("                            Search Directory:\r\n");
      out.write("                            </label>\r\n");
      out.write("                       </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${confDirectory}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <label for='searchConfigurationFilter'>\r\n");
      out.write("                            Filter (Java Regex):\r\n");
      out.write("                            </label>\r\n");
      out.write("                       </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"searchConfigurationFilter\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <label for='searchConfigurationActiveFilesFilter'>\r\n");
      out.write("                            Include Active Files Only:\r\n");
      out.write("                            </label>\r\n");
      out.write("                       </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"checkbox\" name=\"searchConfigurationActiveFilesFilter\" id=\"searchConfigurationActiveFilesFilter\">\r\n");
      out.write("                    </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <label for='searchConfigurationCommentsFilter'>\r\n");
      out.write("                            Include Commented Lines:\r\n");
      out.write("                            </label>\r\n");
      out.write("                       </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"checkbox\" name=\"searchConfigurationCommentsFilter\" id=\"searchConfigurationCommentsFilter\">\r\n");
      out.write("                    </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"submitSearchConfigurationButton\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Search\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"hideSearchConfigurationButton\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Done\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div dojoType=\"dijit.Dialog\" id=\"searchDialog\" title=\"Search\" style=\"display: none\">\r\n");
      out.write("    <form dojoType=\"dijit.form.Form\" id=\"searchForm\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <label>\r\n");
      out.write("                            Search Directory:\r\n");
      out.write("                            </label>\r\n");
      out.write("                       </td>\r\n");
      out.write("                    <td id=\"searchDirectoryDisplay\">\r\n");
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        \r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <label for='searchFileFilter'>\r\n");
      out.write("                            Filter (Java Regex):\r\n");
      out.write("                            </label>\r\n");
      out.write("                       </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"searchFileFilter\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                   <td>\r\n");
      out.write("                       <label for='searchFileList'>\r\n");
      out.write("                           File extension list:\r\n");
      out.write("                           <span id=\"searchFileTooltip\" class=\"warningTooltip\" onmouseover=\"dijit.Tooltip.defaultPosition=['below', 'above']\"></span>\r\n");
      out.write("                        <div class=\"dijitHidden\">\r\n");
      out.write("                            <div data-dojo-type=\"dijit.Tooltip\" data-dojo-props=\"connectId:'searchFileTooltip'\">\r\n");
      out.write("                                <div class=\"warningDialog\">\r\n");
      out.write("                                    The file list requires a comma separated list of regular expressions that specify which files to include. GZIP'd text files are supported.<br/><br/>\r\n");
      out.write("                                    Example regular expression to search for the following:<br/><br/>\r\n");
      out.write("                                    1. All html files<br/>\r\n");
      out.write("                                    2. All css files<br/>\r\n");
      out.write("                                    3. Files ending with .log.[anything].gz<br/><br/>\r\n");
      out.write("                                    .*\\.html,.*\\.css,.*\\.log\\..*\\.gz\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                           </label>\r\n");
      out.write("                      </td>\r\n");
      out.write("                   <td>\r\n");
      out.write("                       <div dojoType=\"dijit.form.ValidationTextBox\" required=\"true\" id=\"searchFileList\">\r\n");
      out.write("                       </div>\r\n");
      out.write("                   </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr class=\"dijitDialogPaneContentArea\">\r\n");
      out.write("                   <td>\r\n");
      out.write("                       <label for='searchRecursively'>\r\n");
      out.write("                           Search Recursively:\r\n");
      out.write("                      </label>\r\n");
      out.write("                  </td>\r\n");
      out.write("                   <td>\r\n");
      out.write("                       <input type=\"checkbox\" name=\"searchRecursively\" id=\"searchRecursively\">\r\n");
      out.write("                   </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("            <button id=\"submitSearchButton\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Search\r\n");
      out.write("            </button>\r\n");
      out.write("            <button id=\"hideSearchButton\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("                Done\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div dojoType=\"net.apachegui.NoCloseDialog\" id=\"searchProgressDialog\" title=\"Searching\" style=\"display: none; width: 450px;\">\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"searchProgressMessage\" style=\"text-align:center\"></div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"dijitDialogPaneActionBar\">\r\n");
      out.write("         <button id=\"searchProgressCancel\" dojoType=\"dijit.form.Button\" type=\"button\">\r\n");
      out.write("             Cancel\r\n");
      out.write("         </button>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
